config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  use_doorkeeper
  

  namespace :api do
    namespace :v1 do
      resources :parada_tiene_segmentos, :only => [:index, :show], :defaults => {:format => "json"}
      resources :paradas, :only => [:index, :show], :defaults => {:format => "json"}
      resources :segmentos, :only => [:index, :show], :defaults => {:format => "json"}
      resources :ruta_contiene_segmentos, :only => [:index, :show], :defaults => {:format => "json"}
      resources :ruta, :only => [:index, :show], :defaults => {:format => "json"} do
        resources :segmentos, :only => [:index, :show], :defaults => {:format => "json"}
      end
      resources :provincia, :only => [:index, :show], :defaults => {:format => "json"}
      resources :empresas, :only => [:index, :show], :defaults => {:format => "json"} do
        resources :ruta, :only => [:index, :show], :defaults => {:format => "json"}
      end
      resources :distritos, :only => [:index, :show], :defaults => {:format => "json"}
      resources :cantons, :only => [:index, :show], :defaults => {:format => "json"}
      get 'ruta/calculate_closest_route/:lat/:long', to: 'ruta#calculate_closest_route', constraints: { lat: /\-*\d+.\d+/ , long: /\-*\d+.\d+/ }, :defaults => {:format => "json"}
      get 'segmentos/calculate_closest_segment/:lat/:long', to: 'segmentos#calculate_closest_segment', constraints: { lat: /\-*\d+.\d+/ , long: /\-*\d+.\d+/ }, :defaults => {:format => "json"}
      get 'paradas/calculate_closest_stop/:lat/:long', to: 'paradas#calculate_closest_stop', constraints: { lat: /\-*\d+.\d+/ , long: /\-*\d+.\d+/ }, :defaults => {:format => "json"}
      get 'paradas/share_stop/:lat/:long(/:desc)', to: 'paradas#share_stop', constraints: { lat: /\-*\d+.\d+/ , long: /\-*\d+.\d+/ }, :defaults => {:format => "json"}
    end
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

end

app/models/ruta_contiene_segmento.rb
class RutaContieneSegmento < ActiveRecord::Base
	belongs_to :ruta
	belongs_to :segmento
end

app/controllers/api/v1/ruta_contiene_segmentos_controller.rb
module Api
  module V1
    class RutaContieneSegmentosController < ApiController
      before_action :set_ruta_contiene_segmento, only: [:show, :edit, :update, :destroy]
      # GET /ruta_contiene_segmentos
      # GET /ruta_contiene_segmentos.json
      def index
        @ruta_contiene_segmentos = RutaContieneSegmento.all
        respond_with @ruta_contiene_segmentos
      end

      # GET /ruta_contiene_segmentos/1
      # GET /ruta_contiene_segmentos/1.json
      def show
        respond_with RutaContieneSegmento.find(params[:id])
      end

      # GET /ruta_contiene_segmentos/new
      def new
        @ruta_contiene_segmento = RutaContieneSegmento.new
      end

      # GET /ruta_contiene_segmentos/1/edit
      def edit
      end

      # POST /ruta_contiene_segmentos
      # POST /ruta_contiene_segmentos.json
      def create
        @ruta_contiene_segmento = RutaContieneSegmento.new(ruta_contiene_segmento_params)

        respond_to do |format|
          if @ruta_contiene_segmento.save
            format.json { render :show, status: :created, location: @ruta_contiene_segmento }
          else
            format.json { render json: @ruta_contiene_segmento.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /ruta_contiene_segmentos/1
      # PATCH/PUT /ruta_contiene_segmentos/1.json
      def update
        respond_to do |format|
          if @ruta_contiene_segmento.update(ruta_contiene_segmento_params)
            format.json { render :show, status: :ok, location: @ruta_contiene_segmento }
          else
            format.json { render json: @ruta_contiene_segmento.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /ruta_contiene_segmentos/1
      # DELETE /ruta_contiene_segmentos/1.json
      def destroy
        @ruta_contiene_segmento.destroy
        respond_to do |format|
          format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_ruta_contiene_segmento
          @ruta_contiene_segmento = RutaContieneSegmento.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def ruta_contiene_segmento_params
          params.require(:ruta_contiene_segmento).permit(:ruta_id, :ruta_Empresa_id, :segmento_id)
        end
    end
  end
end

app/controllers/ruta_contiene_segmentos_controller.rb
class RutaContieneSegmentosController < ApplicationController
  before_action :set_ruta_contiene_segmento, only: [:show, :edit, :update, :destroy]

  # GET /ruta_contiene_segmentos
  # GET /ruta_contiene_segmentos.json
  def index
    @ruta_contiene_segmentos = RutaContieneSegmento.all
  end

  # GET /ruta_contiene_segmentos/1
  # GET /ruta_contiene_segmentos/1.json
  def show
  end

  # GET /ruta_contiene_segmentos/new
  def new
    @ruta_contiene_segmento = RutaContieneSegmento.new
  end

  # GET /ruta_contiene_segmentos/1/edit
  def edit
  end

  # POST /ruta_contiene_segmentos
  # POST /ruta_contiene_segmentos.json
  def create
    @ruta_contiene_segmento = RutaContieneSegmento.new(ruta_contiene_segmento_params)

    respond_to do |format|
      if @ruta_contiene_segmento.save
        format.html { redirect_to @ruta_contiene_segmento, notice: 'Ruta contiene segmento was successfully created.' }
        format.json { render :show, status: :created, location: @ruta_contiene_segmento }
      else
        format.html { render :new }
        format.json { render json: @ruta_contiene_segmento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ruta_contiene_segmentos/1
  # PATCH/PUT /ruta_contiene_segmentos/1.json
  def update
    respond_to do |format|
      if @ruta_contiene_segmento.update(ruta_contiene_segmento_params)
        format.html { redirect_to @ruta_contiene_segmento, notice: 'Ruta contiene segmento was successfully updated.' }
        format.json { render :show, status: :ok, location: @ruta_contiene_segmento }
      else
        format.html { render :edit }
        format.json { render json: @ruta_contiene_segmento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ruta_contiene_segmentos/1
  # DELETE /ruta_contiene_segmentos/1.json
  def destroy
    @ruta_contiene_segmento.destroy
    respond_to do |format|
      format.html { redirect_to ruta_contiene_segmentos_url, notice: 'Ruta contiene segmento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ruta_contiene_segmento
      @ruta_contiene_segmento = RutaContieneSegmento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ruta_contiene_segmento_params
      params.require(:ruta_contiene_segmento).permit(:ruta_id, :ruta_Empresa_id, :segmento_id)
    end
end

app/helpers/ruta_contiene_segmentos_helper.rb
module RutaContieneSegmentosHelper
end

app/views/ruta_contiene_segmentos/_form.html.erb
<%= form_for(@ruta_contiene_segmento) do |f| %>
  <% if @ruta_contiene_segmento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ruta_contiene_segmento.errors.count, "error") %> prohibited this ruta_contiene_segmento from being saved:</h2>

      <ul>
      <% @ruta_contiene_segmento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ruta_id %><br>
    <%= f.number_field :ruta_id %>
  </div>
  <div class="field">
    <%= f.label :ruta_Empresa_id %><br>
    <%= f.number_field :ruta_Empresa_id %>
  </div>
  <div class="field">
    <%= f.label :segmento_id %><br>
    <%= f.number_field :segmento_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ruta_contiene_segmentos/edit.html.erb
<h1>Editing ruta_contiene_segmento</h1>

<%= render 'form' %>

<%= link_to 'Show', @ruta_contiene_segmento %> |
<%= link_to 'Back', ruta_contiene_segmentos_path %>

app/views/ruta_contiene_segmentos/index.html.erb
<h1>Listing ruta_contiene_segmentos</h1>

<table>
  <thead>
    <tr>
      <th>Ruta</th>
      <th>Ruta empresa</th>
      <th>Segmento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ruta_contiene_segmentos.each do |ruta_contiene_segmento| %>
      <tr>
        <td><%= ruta_contiene_segmento.ruta_id %></td>
        <td><%= ruta_contiene_segmento.ruta_Empresa_id %></td>
        <td><%= ruta_contiene_segmento.segmento_id %></td>
        <td><%= link_to 'Show', ruta_contiene_segmento %></td>
        <td><%= link_to 'Edit', edit_ruta_contiene_segmento_path(ruta_contiene_segmento) %></td>
        <td><%= link_to 'Destroy', ruta_contiene_segmento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ruta contiene segmento', new_ruta_contiene_segmento_path %>

app/views/ruta_contiene_segmentos/new.html.erb
<h1>New ruta_contiene_segmento</h1>

<%= render 'form' %>

<%= link_to 'Back', ruta_contiene_segmentos_path %>

app/views/ruta_contiene_segmentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ruta:</strong>
  <%= @ruta_contiene_segmento.ruta_id %>
</p>

<p>
  <strong>Ruta empresa:</strong>
  <%= @ruta_contiene_segmento.ruta_Empresa_id %>
</p>

<p>
  <strong>Segmento:</strong>
  <%= @ruta_contiene_segmento.segmento_id %>
</p>

<%= link_to 'Edit', edit_ruta_contiene_segmento_path(@ruta_contiene_segmento) %> |
<%= link_to 'Back', ruta_contiene_segmentos_path %>