config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  use_doorkeeper
  

  namespace :api do
    namespace :v1 do
      resources :parada_tiene_segmentos, :only => [:index, :show], :defaults => {:format => "json"}
      resources :paradas, :only => [:index, :show], :defaults => {:format => "json"}
      resources :segmentos, :only => [:index, :show], :defaults => {:format => "json"}
      resources :ruta_contiene_segmentos, :only => [:index, :show], :defaults => {:format => "json"}
      resources :ruta, :only => [:index, :show], :defaults => {:format => "json"} do
        resources :segmentos, :only => [:index, :show], :defaults => {:format => "json"}
      end
      resources :provincia, :only => [:index, :show], :defaults => {:format => "json"}
      resources :empresas, :only => [:index, :show], :defaults => {:format => "json"} do
        resources :ruta, :only => [:index, :show], :defaults => {:format => "json"}
      end
      resources :distritos, :only => [:index, :show], :defaults => {:format => "json"}
      resources :cantons, :only => [:index, :show], :defaults => {:format => "json"}
      get 'ruta/calculate_closest_route/:lat/:long', to: 'ruta#calculate_closest_route', constraints: { lat: /\-*\d+.\d+/ , long: /\-*\d+.\d+/ }, :defaults => {:format => "json"}
      get 'segmentos/calculate_closest_segment/:lat/:long', to: 'segmentos#calculate_closest_segment', constraints: { lat: /\-*\d+.\d+/ , long: /\-*\d+.\d+/ }, :defaults => {:format => "json"}
      get 'paradas/calculate_closest_stop/:lat/:long', to: 'paradas#calculate_closest_stop', constraints: { lat: /\-*\d+.\d+/ , long: /\-*\d+.\d+/ }, :defaults => {:format => "json"}
      get 'paradas/share_stop/:lat/:long(/:desc)', to: 'paradas#share_stop', constraints: { lat: /\-*\d+.\d+/ , long: /\-*\d+.\d+/ }, :defaults => {:format => "json"}
    end
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

end

app/models/segmento.rb
class Segmento < ActiveRecord::Base
	has_many :ruta_contiene_segmentos
  	has_many :rutas, through: :ruta_contiene_segmentos

  	before_create lambda{|segmento| segmento.normalize_decimals} 

  	def normalize_decimals
  	  if self.segmento_linea.present?
        s = "LINESTRING("
        self.segmento_linea.points.each do |p|
          lng = p.x.round(6)
	        lat = p.y.round(6)
	      s += "#{lng} #{lat},"
        end
        s = s.chomp(',')
        s += ")"
        self.segmento_linea = s
      end
	end
end

app/controllers/api/v1/segmentos_controller.rb
module Api
  module V1
    class SegmentosController < ApiController
      before_action :set_segmento, only: [:show, :edit, :update, :destroy]

      # GET /segmentos
      # GET /segmentos.json
      def index
        @segmento = Segmento.all
        @segmento = Ruta.find(params[:rutum_id]).segmentos if params[:rutum_id].present?
        respond_with @segmento
      end

      # GET /segmentos/1
      # GET /segmentos/1.json
      def show
        respond_with Segmento.find(params[:id])
      end

      # GET /segmentos/new
      def new
        respond_with Segmento.new
      end

      # GET /segmentos/1/edit
      def edit
      end

      # POST /segmentos
      # POST /segmentos.json
      def create
        @segmento = Segmento.new(segmento_params)

        respond_to do |format|
          if @segmento.save
            format.json { render :show, status: :created, location: @segmento }
          else
            format.json { render json: @segmento.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /segmentos/1
      # PATCH/PUT /segmentos/1.json
      def update
        respond_to do |format|
          if @segmento.update(segmento_params)
            format.json { render :show, status: :ok, location: @segmento }
          else
            format.json { render json: @segmento.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /segmentos/1
      # DELETE /segmentos/1.json
      def destroy
        @segmento.destroy
        respond_to do |format|
          format.json { head :no_content }
        end
      end

      # Method for calculating the closest route
      def calculate_closest_segment
        respond_with Segmento.find_by_sql("SELECT s.nombre, ST_AsText(s.segmento_linea) AS segmento
          FROM segmentos s 
          WHERE ST_DWithin (ST_GeomFromText('POINT(#{params[:long]} #{params[:lat]})', 4326), s.segmento_linea, 5000) 
          ORDER BY ST_Distance (ST_GeomFromText('POINT(#{params[:long]} #{params[:lat]})', 4326), s.segmento_linea)LIMIT 1")
      end

      def calculate_closest_segment_with(lat, long)
        
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_segmento
          @segmento = Segmento.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def segmento_params
          params.require(:segmento).permit(:nombre, :segmento_linea)
        end
    end
  end
end

app/controllers/segmentos_controller.rb
class SegmentosController < ApplicationController
  before_action :set_segmento, only: [:show, :edit, :update, :destroy]

  # GET /segmentos
  # GET /segmentos.json
  def index
    @segmentos = Segmento.all
  end

  # GET /segmentos/1
  # GET /segmentos/1.json
  def show
  end

  # GET /segmentos/new
  def new
    @segmento = Segmento.new
  end

  # GET /segmentos/1/edit
  def edit
  end

  # POST /segmentos
  # POST /segmentos.json
  def create
    @segmento = Segmento.new(segmento_params)

    respond_to do |format|
      if @segmento.save
        format.html { redirect_to @segmento, notice: 'Segmento was successfully created.' }
        format.json { render :show, status: :created, location: @segmento }
      else
        format.html { render :new }
        format.json { render json: @segmento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /segmentos/1
  # PATCH/PUT /segmentos/1.json
  def update
    respond_to do |format|
      if @segmento.update(segmento_params)
        format.html { redirect_to @segmento, notice: 'Segmento was successfully updated.' }
        format.json { render :show, status: :ok, location: @segmento }
      else
        format.html { render :edit }
        format.json { render json: @segmento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /segmentos/1
  # DELETE /segmentos/1.json
  def destroy
    @segmento.destroy
    respond_to do |format|
      format.html { redirect_to segmentos_url, notice: 'Segmento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_segmento
      @segmento = Segmento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def segmento_params
      params.require(:segmento).permit(:nombre, :segmento_linea)
    end
end

app/helpers/segmentos_helper.rb
module SegmentosHelper
end

app/views/segmentos/_form.html.erb
<%= form_for(@segmento) do |f| %>
  <% if @segmento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@segmento.errors.count, "error") %> prohibited this segmento from being saved:</h2>

      <ul>
      <% @segmento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :segmento_linea %><br>
    <%= f.text_field :segmento_linea %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/segmentos/edit.html.erb
<h1>Editing segmento</h1>

<%= render 'form' %>

<%= link_to 'Show', @segmento %> |
<%= link_to 'Back', segmentos_path %>

app/views/segmentos/index.html.erb
<h1>Listing segmentos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Segmento linea</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @segmentos.each do |segmento| %>
      <tr>
        <td><%= segmento.nombre %></td>
        <td><%= segmento.segmento_linea %></td>
        <td><%= link_to 'Show', segmento %></td>
        <td><%= link_to 'Edit', edit_segmento_path(segmento) %></td>
        <td><%= link_to 'Destroy', segmento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Segmento', new_segmento_path %>

app/views/segmentos/new.html.erb
<h1>New segmento</h1>

<%= render 'form' %>

<%= link_to 'Back', segmentos_path %>

app/views/segmentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @segmento.nombre %>
</p>

<p>
  <strong>Segmento linea:</strong>
  <%= @segmento.segmento_linea %>
</p>

<%= link_to 'Edit', edit_segmento_path(@segmento) %> |
<%= link_to 'Back', segmentos_path %>