config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  use_doorkeeper
  

  namespace :api do
    namespace :v1 do
      resources :parada_tiene_segmentos, :only => [:index, :show], :defaults => {:format => "json"}
      resources :paradas, :only => [:index, :show], :defaults => {:format => "json"}
      resources :segmentos, :only => [:index, :show], :defaults => {:format => "json"}
      resources :ruta_contiene_segmentos, :only => [:index, :show], :defaults => {:format => "json"}
      resources :ruta, :only => [:index, :show], :defaults => {:format => "json"} do
        resources :segmentos, :only => [:index, :show], :defaults => {:format => "json"}
      end
      resources :provincia, :only => [:index, :show], :defaults => {:format => "json"}
      resources :empresas, :only => [:index, :show], :defaults => {:format => "json"} do
        resources :ruta, :only => [:index, :show], :defaults => {:format => "json"}
      end
      resources :distritos, :only => [:index, :show], :defaults => {:format => "json"}
      resources :cantons, :only => [:index, :show], :defaults => {:format => "json"}
      get 'ruta/calculate_closest_route/:lat/:long', to: 'ruta#calculate_closest_route', constraints: { lat: /\-*\d+.\d+/ , long: /\-*\d+.\d+/ }, :defaults => {:format => "json"}
      get 'segmentos/calculate_closest_segment/:lat/:long', to: 'segmentos#calculate_closest_segment', constraints: { lat: /\-*\d+.\d+/ , long: /\-*\d+.\d+/ }, :defaults => {:format => "json"}
      get 'paradas/calculate_closest_stop/:lat/:long', to: 'paradas#calculate_closest_stop', constraints: { lat: /\-*\d+.\d+/ , long: /\-*\d+.\d+/ }, :defaults => {:format => "json"}
      get 'paradas/share_stop/:lat/:long(/:desc)', to: 'paradas#share_stop', constraints: { lat: /\-*\d+.\d+/ , long: /\-*\d+.\d+/ }, :defaults => {:format => "json"}
    end
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

end

app/models/canton.rb
class Canton < ActiveRecord::Base
end

app/controllers/api/v1/cantons_controller.rb
module Api
  module V1
    class CantonsController < ApiController
      before_action :set_canton, only: [:show, :edit, :update, :destroy]
      
      
      def index
        @cantons =  Canton.all
        respond_with @cantons
      end

      # GET /cantons/1
      # GET /cantons/1.json
      def show
        respond_with Canton.find(params[:id])
      end

      # GET /cantons/new
      def new
       @canton = Canton.new
       #respond_with @canton
      end

      # GET /cantons/1/edit
      def edit
      end

      # POST /cantons
      # POST /cantons.json
      def create
        @canton = Canton.new(canton_params)
        respond_to do |format|
          if @canton.save
            format.json { render :show, status: :created, location: @canton }
          else
            format.json { render json: @canton.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /cantons/1
      # PATCH/PUT /cantons/1.json
      def update
        respond_to do |format|
          if @canton.update(canton_params)
            format.json { render :show, status: :ok, location: @canton }
          else
            format.json { render json: @canton.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /cantons/1
      # DELETE /cantons/1.json
      def destroy
        @canton.destroy
        respond_to do |format|
          format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_canton
          @canton = Canton.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def canton_params
          params.require(:canton).permit(:id, :nombre, :provincia_id)
        end
    end
  end
end

app/controllers/cantons_controller.rb
class CantonsController < ApplicationController
  before_action :set_canton, only: [:show, :edit, :update, :destroy]
  
  # GET /cantons
  # GET /cantons.json
  def index
    @cantons = Canton.all
  end

  # GET /cantons/1
  # GET /cantons/1.json
  def show
  end

  # GET /cantons/new
  def new
    @canton = Canton.new
  end

  # GET /cantons/1/edit
  def edit
  end

  # POST /cantons
  # POST /cantons.json
  def create
    @canton = Canton.new(canton_params)

    respond_to do |format|
      if @canton.save
        format.html { redirect_to @canton, notice: 'Canton was successfully created.' }
        format.json { render :show, status: :created, location: @canton }
      else
        format.html { render :new }
        format.json { render json: @canton.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cantons/1
  # PATCH/PUT /cantons/1.json
  def update
    respond_to do |format|
      if @canton.update(canton_params)
        format.html { redirect_to @canton, notice: 'Canton was successfully updated.' }
        format.json { render :show, status: :ok, location: @canton }
      else
        format.html { render :edit }
        format.json { render json: @canton.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cantons/1
  # DELETE /cantons/1.json
  def destroy
    @canton.destroy
    respond_to do |format|
      format.html { redirect_to cantons_url, notice: 'Canton was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_canton
      @canton = Canton.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def canton_params
      params.require(:canton).permit(:id, :nombre, :provincia_id)
    end
end

app/helpers/cantons_helper.rb
module CantonsHelper
end

app/views/cantons/_form.html.erb
<%= form_for(@canton) do |f| %>
  <% if @canton.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@canton.errors.count, "error") %> prohibited this canton from being saved:</h2>

      <ul>
      <% @canton.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :provincia_id %><br>
    <%= f.number_field :provincia_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cantons/edit.html.erb
<h1>Editing canton</h1>

<%= render 'form' %>

<%= link_to 'Show', @canton %> |
<%= link_to 'Back', cantons_path %>

app/views/cantons/index.html.erb
<h1>Listing cantons</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Nombre</th>
      <th>Provincia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cantons.each do |canton| %>
      <tr>
        <td><%= canton.id %></td>
        <td><%= canton.nombre %></td>
        <td><%= canton.provincia_id %></td>
        <td><%= link_to 'Show', canton %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/cantons/new.html.erb
<h1>New canton</h1>

<%= render 'form' %>

<%= link_to 'Back', cantons_path %>

app/views/cantons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @canton.id %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @canton.nombre %>
</p>

<p>
  <strong>Provincia:</strong>
  <%= @canton.provincia_id %>
</p>

<%= link_to 'Edit', edit_canton_path(@canton) %> |
<%= link_to 'Back', cantons_path %>