config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  use_doorkeeper
  

  namespace :api do
    namespace :v1 do
      resources :parada_tiene_segmentos, :only => [:index, :show], :defaults => {:format => "json"}
      resources :paradas, :only => [:index, :show], :defaults => {:format => "json"}
      resources :segmentos, :only => [:index, :show], :defaults => {:format => "json"}
      resources :ruta_contiene_segmentos, :only => [:index, :show], :defaults => {:format => "json"}
      resources :ruta, :only => [:index, :show], :defaults => {:format => "json"} do
        resources :segmentos, :only => [:index, :show], :defaults => {:format => "json"}
      end
      resources :provincia, :only => [:index, :show], :defaults => {:format => "json"}
      resources :empresas, :only => [:index, :show], :defaults => {:format => "json"} do
        resources :ruta, :only => [:index, :show], :defaults => {:format => "json"}
      end
      resources :distritos, :only => [:index, :show], :defaults => {:format => "json"}
      resources :cantons, :only => [:index, :show], :defaults => {:format => "json"}
      get 'ruta/calculate_closest_route/:lat/:long', to: 'ruta#calculate_closest_route', constraints: { lat: /\-*\d+.\d+/ , long: /\-*\d+.\d+/ }, :defaults => {:format => "json"}
      get 'segmentos/calculate_closest_segment/:lat/:long', to: 'segmentos#calculate_closest_segment', constraints: { lat: /\-*\d+.\d+/ , long: /\-*\d+.\d+/ }, :defaults => {:format => "json"}
      get 'paradas/calculate_closest_stop/:lat/:long', to: 'paradas#calculate_closest_stop', constraints: { lat: /\-*\d+.\d+/ , long: /\-*\d+.\d+/ }, :defaults => {:format => "json"}
      get 'paradas/share_stop/:lat/:long(/:desc)', to: 'paradas#share_stop', constraints: { lat: /\-*\d+.\d+/ , long: /\-*\d+.\d+/ }, :defaults => {:format => "json"}
    end
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end

end

app/models/parada.rb
class Parada < ActiveRecord::Base
	before_create lambda{|parada| parada.normalize_decimals} 

	def normalize_decimals
	  if self.punto_parada.present?
		lat = self.punto_parada.x.round(6)
		lng = self.punto_parada.y.round(6)
		normalized_stop = "POINT(#{lat} #{lng})"
	    self.punto_parada = normalized_stop
	  end
	end
end

app/controllers/api/v1/paradas_controller.rb
module Api
  module V1
    class ParadasController < ApiController
      before_action :set_parada, only: [:show, :edit, :update, :destroy]
      # GET /paradas
      # GET /paradas.json
      def index
        @paradas = Parada.all
        respond_with @paradas
      end

      # GET /paradas/1
      # GET /paradas/1.json
      def show
        respond_with Parada.find(params[:id])
      end

      # GET /paradas/new
      def new
        @parada = Parada.new
      end

      # GET /paradas/1/edit
      def edit
      end

      # POST /paradas
      # POST /paradas.json
      def create
        @parada = Parada.new(parada_params)

        respond_to do |format|
          if @parada.save
            format.json { render :show, status: :created, location: @parada }
          else
            format.json { render json: @parada.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /paradas/1
      # PATCH/PUT /paradas/1.json
      def update
        respond_to do |format|
          if @parada.update(parada_params)
            format.json { render :show, status: :ok, location: @parada }
          else
            format.json { render json: @parada.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /paradas/1
      # DELETE /paradas/1.json
      def destroy
        @parada.destroy
        respond_to do |format|
          format.json { head :no_content }
        end
      end

      def calculate_closest_stop
         # wgs84_proj4 = '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs'
         # wgs84_factory = RGeo::Geographic.spherical_factory(:srid => 4326, :proj4 => wgs84_proj4)
         # p = wgs84_factory.point(-84.08884599999999,9.890134) 
         respond_with  Parada.find_by_sql("SELECT a.desc, ST_AsText(a.punto_parada) AS punto_parada
          FROM paradas a 
          WHERE ST_DWithin (ST_GeomFromText('POINT(#{params[:long]} #{params[:lat]})', 4326), a.punto_parada, 5000) 
          AND a.activa = true
          ORDER BY ST_Distance(ST_GeomFromText('POINT(#{params[:long]} #{params[:lat]})', 4326), a.punto_parada) LIMIT 1")

      end

      def share_stop
        parada = Parada.new
        parada.punto_parada = "POINT(#{params[:lat]} #{params[:long]})"
        parada.desc = params[:desc] if params[:desc].present?
        if parada.save
         render :json  => parada.to_json
        else
          render :json  => {:errors => parada.errors.full_messages }
        end
      end
      
      private
        # Use callbacks to share common setup or constraints between actions.
        def set_parada
          @parada = Parada.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def parada_params
          params.require(:parada).permit(:desc, :ruta_img, :punto_parada, :activa)
        end
    end
  end
end

app/controllers/paradas_controller.rb
class ParadasController < ApplicationController
  before_action :set_parada, only: [:show, :edit, :update, :destroy]

  # GET /paradas
  # GET /paradas.json
  def index
    @paradas = Parada.all
  end

  # GET /paradas/1
  # GET /paradas/1.json
  def show
  end

  # GET /paradas/new
  def new
    @parada = Parada.new
  end

  # GET /paradas/1/edit
  def edit
  end

  # POST /paradas
  # POST /paradas.json
  def create
    @parada = Parada.new(parada_params)

    respond_to do |format|
      if @parada.save
        format.html { redirect_to @parada, notice: 'Parada was successfully created.' }
        format.json { render :show, status: :created, location: @parada }
      else
        format.html { render :new }
        format.json { render json: @parada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paradas/1
  # PATCH/PUT /paradas/1.json
  def update
    respond_to do |format|
      if @parada.update(parada_params)
        format.html { redirect_to @parada, notice: 'Parada was successfully updated.' }
        format.json { render :show, status: :ok, location: @parada }
      else
        format.html { render :edit }
        format.json { render json: @parada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paradas/1
  # DELETE /paradas/1.json
  def destroy
    @parada.destroy
    respond_to do |format|
      format.html { redirect_to paradas_url, notice: 'Parada was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parada
      @parada = Parada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parada_params
      params.require(:parada).permit(:desc, :ruta_img, :punto_parada)
    end
end

app/helpers/paradas_helper.rb
module ParadasHelper
end

app/views/paradas/_form.html.erb
<%= form_for(@parada) do |f| %>
  <% if @parada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parada.errors.count, "error") %> prohibited this parada from being saved:</h2>

      <ul>
      <% @parada.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :ruta_img %><br>
    <%= f.text_field :ruta_img %>
  </div>
  <div class="field">
    <%= f.label :punto_parada %><br>
    <%= f.text_field :punto_parada %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paradas/edit.html.erb
<h1>Editing parada</h1>

<%= render 'form' %>

<%= link_to 'Show', @parada %> |
<%= link_to 'Back', paradas_path %>

app/views/paradas/index.html.erb
<h1>Listing paradas</h1>

<table>
  <thead>
    <tr>
      <th>Desc</th>
      <th>Ruta img</th>
      <th>Punto parada</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paradas.each do |parada| %>
      <tr>
        <td><%= parada.desc %></td>
        <td><%= parada.ruta_img %></td>
        <td><%= parada.punto_parada %></td>
        <td><%= link_to 'Show', parada %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/paradas/new.html.erb
<h1>New parada</h1>

<%= render 'form' %>

<%= link_to 'Back', paradas_path %>

app/views/paradas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Desc:</strong>
  <%= @parada.desc %>
</p>

<p>
  <strong>Ruta img:</strong>
  <%= @parada.ruta_img %>
</p>

<p>
  <strong>Punto parada:</strong>
  <%= @parada.punto_parada %>
</p>

<%= link_to 'Edit', edit_parada_path(@parada) %> |
<%= link_to 'Back', paradas_path %>